### ISSUE TITLE
Keystone application cannot run with appmetrics enabled trace

### ISSUE THREAD

**Issue by xiaoshimimi** [RuntimeTools/appmetrics#120]
Tested appmetrics with latest keystone application: 

https://github.com/keystonejs/keystone

with 'trace' enabled, visit http://ip:port, there will be a exception, and the page cannot load:
**Screenshot**
![defect_number_keystone1](https://cloud.githubusercontent.com/assets/5269532/11865288/1393ab16-a4de-11e5-8a53-7db390a10ebd.PNG)

**Exception:**
```
called_non_callable Error thrown for request: /
TypeError: undefined is not a function
    at exports.initLocals (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/route        s/middleware.js:35:2)
    at f (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_modules/ibm-apm/n        ode_modules/appmetrics/probes/trace-probe.js:120:26)
    at async.eachSeries.asyncFinished (/opt/node-v0.10.33/sample/keystoneJS/keys        tonejs/node_modules/keystone/node_modules/grappling-hook/index.js:239:24)
    at iterate (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_modules/key        stone/node_modules/grappling-hook/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/        node_modules/keystone/node_modules/grappling-hook/node_modules/async/lib/async.j        s:162:9)
    at iterateAsyncMiddleware (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/n        ode_modules/keystone/node_modules/grappling-hook/index.js:225:8)
    at /opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_modules/keystone/nod        e_modules/grappling-hook/index.js:585:5
    at dezalgofy (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_modules/k        eystone/node_modules/grappling-hook/index.js:192:2)
    at methods.callHook (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_mo        dules/keystone/node_modules/grappling-hook/index.js:584:4)
    at /opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_modules/keystone/lib        /core/mount.js:444:12
    at Layer.handle [as handle_request] (/opt/node-v0.10.33/sample/keystoneJS/ke        ystonejs/node_modules/keystone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_modules        /keystone/node_modules/express/lib/router/index.js:312:13)
    at /opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_modules/keystone/nod        e_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/        node_modules/keystone/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_modules/keysto        ne/node_modules/express/lib/router/index.js:271:10)
    at frameGuard (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_modules/        keystone/lib/security/frameGuard.js:22:3)
    at Layer.handle [as handle_request] (/opt/node-v0.10.33/sample/keystoneJS/ke        ystonejs/node_modules/keystone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_modules        /keystone/node_modules/express/lib/router/index.js:312:13)
    at /opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_modules/keystone/nod        e_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/        node_modules/keystone/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_modules/keysto        ne/node_modules/express/lib/router/index.js:271:10)
    at exports.persist (/opt/node-v0.10.33/sample/keystoneJS/keystonejs/node_mod        ules/keystone/lib/session.js:190:3)
```

**Comment by xiaoshimimi** [comment]
problem fixed
