### ISSUE TITLE
'config is not defined' when calling setConfig()

### ISSUE THREAD

**Issue by DanCunnington** [RuntimeTools/appmetrics#124]
When attempting to set the configuration of trace as follows:

```javascript
appmetrics.enable('trace');
appmetrics.setConfig('trace', {'includeModules': ['keystone']});
```

The following error is produced
```
C:\Users\IBM_ADMIN\Documents\appmetricsKeystoneIssue\testapp\node_modules\appmetrics\lib\probe.js:41
                        config[prop] = newConfig[prop];
                        ^
ReferenceError: config is not defined
    at TraceProbe.Probe.setConfig (C:\Users\IBM_ADMIN\Documents\appmetricsKeystoneIssue\testapp\node_modules\appmetrics\lib\probe.js:41:4)
    at C:\Users\IBM_ADMIN\Documents\appmetricsKeystoneIssue\testapp\node_modules\appmetrics\index.js:209:11
    at Array.forEach (native)
    at Object.module.exports.setConfig (C:\Users\IBM_ADMIN\Documents\appmetricsKeystoneIssue\testapp\node_modules\appmetrics\index.js:207:10)
    at Object.<anonymous> (C:\Users\IBM_ADMIN\Documents\appmetricsKeystoneIssue\testapp\routes\views\index.js:6:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at C:\Users\IBM_ADMIN\Documents\appmetricsKeystoneIssue\testapp\node_modules\keystone\lib\core\importer.js:42:23
    at Array.forEach (native)
    at importer (C:\Users\IBM_ADMIN\Documents\appmetricsKeystoneIssue\testapp\node_modules\keystone\lib\core\importer.js:32:26)
    at Object.<anonymous> (C:\Users\IBM_ADMIN\Documents\appmetricsKeystoneIssue\testapp\routes\index.js:31:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\IBM_ADMIN\Documents\appmetricsKeystoneIssue\testapp\keystone.js:47:24)
```

**Comment by tunniclm** [comment]
With the merging of #126, is this issue now fixed/ready to close?
