### ISSUE TITLE
TypeError thrown using appmetrics v1.0.6

### ISSUE THREAD

**Issue by cbridgha** [RuntimeTools/appmetrics#135]
I get this error thrown while starting a profiling session on Node (v0.12.7).

We discovered a workaround by forcing an npm install of appmetrics v1.0.3 or earlier. 
By default, v1.0.6 is currently installed.   This was on Windows, and was also recreated on iOS.

[01/21/16 15:32:11] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 1.0.6.201601201151 (Agent Core 3.0.6.201511031005)
[01/21/16 15:32:11] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker chuckpad540:1883
C:\Users\cbridgha\AppData\Roaming\npm\node_modules\appmetrics\lib\aspect.js:54
		var existing = target[methodName];
		                     ^
TypeError: Cannot read property 'on' of undefined
    at C:\Users\cbridgha\AppData\Roaming\npm\node_modules\appmetrics\lib\aspect.js:54:24
    at Array.forEach (native)
    at Object.exports.before (C:\Users\cbridgha\AppData\Roaming\npm\node_modules\appmetrics\lib\aspect.js:53:8)
    at SocketioProbe.attach (C:\Users\cbridgha\AppData\Roaming\npm\node_modules\appmetrics\probes\socketio-probe.js:68:10)
    at C:\Users\cbridgha\AppData\Roaming\npm\node_modules\appmetrics\index.js:107:21
    at Module.newFunc (C:\Users\cbridgha\AppData\Roaming\npm\node_modules\appmetrics\lib\aspect.js:100:12)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\cbridgha\git\nodejs-chat\server.js:5:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by tobespc** [comment]
umm, ok, I've tried exactly the same configuration and I don't get the error so will keep on digging

**Comment by tobespc** [comment]
this works on the latest version of socket.io (v1.4.4) but is failing on the 0.9.17 that you are using

**Comment by tobespc** [comment]
1.0.2 is the minimum version of socket.io that works with the appmetrics socket.io-probe

**Comment by tobespc** [comment]
I'll document the minimum supported versions

**Comment by tobespc** [comment]
https://github.com/RuntimeTools/appmetrics/wiki/Limitations-and-known-problems
