### ISSUE TITLE
Confused with configuring appmetrics-elk

### ISSUE THREAD

**Issue by sameerpanicker** [RuntimeTools/appmetrics#177]
I am referring to this link - https://www.npmjs.com/package/appmetrics-elk

I have completed the Installation step. I am totally confused how to do the next step. 
ie.. var appmetrics = require('appmetrics-elk').monitor();
appmetrics.disable('mysql');

Where should I write this code ? Please help

**Comment by sameerpanicker** [comment]
Any update on this issue

**Comment by tobespc** [comment]
@sameerpanicker  To use that code, you simply need to add it to the top of your main node module, index.js for example.

There is a video guide available here https://www.youtube.com/watch?v=Dgllh4Xb7d8 that show this in action including how to update your code

**Comment by sameerpanicker** [comment]
I have already seen this video. I am using this on Windows and I tried editing both the files...index.js and app.js....still no luck.

**Comment by seabaylea** [comment]
Hi @sameerpanicker :

As @tobespc says, once you have Elasticsearch and Kibana installed and running, you should just need to take whichever file you use to start your application, and add the following line to the start:
```js
var elk = require('appmetrics-elk').monitor();
```
This assumes that Elasticsearch is running on your localhost and has no security. If you need to configure the connection, we can provide instructions on how to do that.

When the application starts, you should see the following written to the console:
```
[Mon Mar 21 11:05:37 2016] com.ibm.diagnostics.healthcenter.loader INFO: Node Application Metrics 1.0.7.201602110606 (Agent Core 3.0.6.201511030958)
[Mon Mar 21 11:05:37 2016] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to broker localhost:1883
```

If Elasticsearch cannot be found, you should also see this:
```
Elasticsearch ERROR: 2016-03-21T11:05:38Z
  Error: Request error, retrying
  HEAD http://localhost:9200/appmetrics => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (/node_modules/appmetrics-elk/node_modules/elasticsearch/src/lib/log.js:226:56)
```

Do you see any output when you start your application?

**Comment by sameerpanicker** [comment]
I added this line to the start of elasticsearch.yml and filebeat.yml file. When I tried running the application, got this error 

Exception in thread "main" SettingsException[Failed to load settings from [elast
icsearch.yml]]; nested: ElasticsearchParseException[malformed, expected settings
 to start with 'object', instead was [VALUE_STRING]];
Likely root cause: ElasticsearchParseException[malformed, expected settings to s
tart with 'object', instead was [VALUE_STRING]]
        at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(
XContentSettingsLoader.java:65)
        at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(
XContentSettingsLoader.java:45)
        at org.elasticsearch.common.settings.loader.YamlSettingsLoader.load(Yaml
SettingsLoader.java:46)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Set
tings.java:1074)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Setti
ngs.java:1061)
        at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvir
onment(InternalSettingsPreparer.java:88)
        at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:107)
        at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:100)
        at org.elasticsearch.bootstrap.BootstrapCLIParser.<init>(BootstrapCLIPar
ser.java:48)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:241)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

**Comment by seabaylea** [comment]
Hi @sameerpanicker 

The following line:
```js
var elk = require('appmetrics-elk').monitor();
```
needs to be added to the start of the Node.js application that you want to monitor, not to the Elasticsearch instance that's going to store the data.

If you take the following sample application:
```js
var elk = require('appmetrics-elk').monitor();

http.createServer(function handler(req, res) {
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end('Hello World');
}).listen(8080);
console.log('Server running at ' + host + ':' + port);
```
and save it as `app.js`, you can then run it using:
```sh
node app.js
```
This should then send the data to your local Elasticsearch instance.

**Comment by sameerpanicker** [comment]
When I tried this in the app.js file....got this error..

C:\Program Files\nodejs>node.exe app.js
[03/23/16 16:19:28] com.ibm.diagnostics.healthcenter.loader INFO: Node Applicati
on Metrics 1.0.7.201602110606 (Agent Core 3.0.6.201511031005)
[03/23/16 16:19:28] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to br
oker localhost:1883
C:\Program Files\nodejs\app.js:3
http.createServer(function handler(req, res) {
^

ReferenceError: http is not defined
    at Object.<anonymous> (C:\Program Files\nodejs\app.js:3:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by sameerpanicker** [comment]
Also getting this warning...

Elasticsearch WARNING: 2016-03-23T21:19:52Z
  Unable to revive connection: http://localhost:9200/

How can I change the host value ???

**Comment by seabaylea** [comment]
Sorry, the test case should have been:

```js
var elk = require('appmetrics-elk').monitor();
var http = require('http');
http.createServer(function handler(req, res) {
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end('Hello World');
}).listen(8080);
console.log('Server running');
```

You can set the host for the Elasticsearch instance by passing a configuration object to the `monitor()`method, e.g.:

```js
var config = {
    host: 'http://myhost.com:9200'
}
var elk = require('appmetrics-elk').monitor();
var http = require('http');
http.createServer(function handler(req, res) {
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end('Hello World');
}).listen(8080);
console.log('Server running');
```
where you just change 'myhost.com' to the desired location.

**Comment by sameerpanicker** [comment]
I truely appreciate your help. Since, this is something new for me....I am trying to learn.

With your above solution,something worked but still NO success. Still it is trying to connect to some default port.

Also, what will be the index name where these info will be stored under?

C:\Program Files\nodejs>node.exe app.js
[03/24/16 11:43:36] com.ibm.diagnostics.healthcenter.loader INFO: Node Applicati
on Metrics 1.0.7.201602110606 (Agent Core 3.0.6.201511031005)
[03/24/16 11:43:36] com.ibm.diagnostics.healthcenter.mqtt INFO: Connecting to br
oker localhost:1883
Server running
Elasticsearch ERROR: 2016-03-24T16:43:38Z
  Error: Request error, retrying
  POST http://localhost:9200/.kibana/config/_search/exists => connect ECONNREFUS
ED **127.0.0.1:9200**
      at Log.error (C:\Program Files\nodejs\node_modules\appmetrics-elk\node_mod
ules\elasticsearch\src\lib\log.js:226:56)
      at checkRespForFailure (C:\Program Files\nodejs\node_modules\appmetrics-el
k\node_modules\elasticsearch\src\lib\transport.js:244:18)
      at HttpConnector.<anonymous> (C:\Program Files\nodejs\node_modules\appmetr
ics-elk\node_modules\elasticsearch\src\lib\connectors\http.js:153:7)
      at ClientRequest.wrapper (C:\Program Files\nodejs\node_modules\appmetrics-
elk\node_modules\elasticsearch\node_modules\lodash\index.js:3095:19)
      at emitOne (events.js:77:13)
      at ClientRequest.emit (events.js:169:7)
      at Socket.socketErrorListener (_http_client.js:256:9)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at emitErrorNT (net.js:1250:8)

Elasticsearch ERROR: 2016-03-24T16:43:38Z
  Error: Request error, retrying
  POST http://localhost:9200/.kibana/index-pattern/_search/exists => connect ECO
NNREFUSED 127.0.0.1:9200
      at Log.error (C:\Program Files\nodejs\node_modules\appmetrics-elk\node_mod
ules\elasticsearch\src\lib\log.js:226:56)
      at checkRespForFailure (C:\Program Files\nodejs\node_modules\appmetrics-el
k\node_modules\elasticsearch\src\lib\transport.js:244:18)
      at HttpConnector.<anonymous> (C:\Program Files\nodejs\node_modules\appmetr
ics-elk\node_modules\elasticsearch\src\lib\connectors\http.js:153:7)
      at ClientRequest.wrapper (C:\Program Files\nodejs\node_modules\appmetrics-
elk\node_modules\elasticsearch\node_modules\lodash\index.js:3095:19)
      at emitOne (events.js:77:13)
      at ClientRequest.emit (events.js:169:7)
      at Socket.socketErrorListener (_http_client.js:256:9)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at emitErrorNT (net.js:1250:8)

Elasticsearch ERROR: 2016-03-24T16:43:38Z
  Error: Request error, retrying
  HEAD http://localhost:9200/appmetrics => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (C:\Program Files\nodejs\node_modules\appmetrics-elk\node_mod
ules\elasticsearch\src\lib\log.js:226:56)
      at checkRespForFailure (C:\Program Files\nodejs\node_modules\appmetrics-el
k\node_modules\elasticsearch\src\lib\transport.js:244:18)
      at HttpConnector.<anonymous> (C:\Program Files\nodejs\node_modules\appmetr
ics-elk\node_modules\elasticsearch\src\lib\connectors\http.js:153:7)
      at ClientRequest.wrapper (C:\Program Files\nodejs\node_modules\appmetrics-
elk\node_modules\elasticsearch\node_modules\lodash\index.js:3095:19)
      at emitOne (events.js:77:13)
      at ClientRequest.emit (events.js:169:7)
      at Socket.socketErrorListener (_http_client.js:256:9)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at emitErrorNT (net.js:1250:8)

Elasticsearch WARNING: 2016-03-24T16:43:39Z
  No living connections

Elasticsearch WARNING: 2016-03-24T16:43:39Z
  Unable to revive connection: **http://localhost:9200/**

**Comment by tunniclm** [comment]
I think this was another typo, @seabaylea described passing config to `monitor()` but I think forgot to update the code sample.

```js
var config = {
    host: 'http://myhost.com:9200'
}
var elk = require('appmetrics-elk').monitor(config);
var http = require('http');
http.createServer(function handler(req, res) {
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end('Hello World');
}).listen(8080);
console.log('Server running');
```

See also, the module readme at https://www.npmjs.com/package/appmetrics-elk

**Comment by sameerpanicker** [comment]
Thanks a lot. It worked fine now.

**Comment by seabaylea** [comment]
Glad we could finally get working for you!
