### ISSUE TITLE
TypeError: Cannot read property '1' of null when running with REPL

### ISSUE THREAD

**Issue by seabaylea** [RuntimeTools/appmetrics#28]
When running the following in REPL with the 1.0.2 development line:
```sh
> node
> var appmetrics = require('appmetrics');
```
The following TypeError is seen:
```sh
TypeError: Cannot read property '1' of null
    at getRootModuleDir (C:\Users\tunniclm\workspaces\jtctools\runtime.tools\build\Release\deploy\internal\node_modules\appmetrics\probes\trace-probe.js:187:30)
    at Object.<anonymous> (C:\Users\tunniclm\workspaces\jtctools\runtime.tools\build\Release\deploy\internal\node_modules\appmetrics\probes\trace-probe.js:198:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\tunniclm\workspaces\jtctools\runtime.tools\build\Release\deploy\internal\node_modules\appmetrics\index.js:44:25
    at Array.forEach (native)
```

This is caused by the redundant/unused `getRootModuleDir()` function in `probes\trace-probe.js`, which can be removed.

**Comment by seabaylea** [comment]
Fixed by PR #29 (Remove redundant getRootModuleDir code)
