### ISSUE TITLE
expressProbe failed to process request

### ISSUE THREAD

**Issue by xiaoshimimi** [RuntimeTools/appmetrics#324]
appmetrics v1.1.2
node.js v4.4.5
application: Acmeair 0.0.1
with trace enabled

When I login in UI, there is error in console:

```
TypeError: Cannot read property '0' of undefined
    at ExpressProbe.requestStart (/root/NodeApps/acmeair-webapp-nodejs/node_modules/knj-plugin/node_modules/appmetrics/probes/express-probe.js:95:44)
    at aspect.aroundCallback.methodArgs.statusCode (/root/NodeApps/acmeair-webapp-nodejs/node_modules/knj-plugin/node_modules/appmetrics/probes/express-probe.js:57:16)
    at args.(anonymous function) (/root/NodeApps/acmeair-webapp-nodejs/node_modules/knj-plugin/node_modules/appmetrics/lib/aspect.js:26:4)
    at callbacks (/root/NodeApps/acmeair-webapp-nodejs/node_modules/express/lib/router/index.js:165:11)
    at param (/root/NodeApps/acmeair-webapp-nodejs/node_modules/express/lib/router/index.js:139:11)
    at pass (/root/NodeApps/acmeair-webapp-nodejs/node_modules/express/lib/router/index.js:146:5)
    at Router._dispatch (/root/NodeApps/acmeair-webapp-nodejs/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/root/NodeApps/acmeair-webapp-nodejs/node_modules/express/lib/router/index.js:33:10)
    at next (/root/NodeApps/acmeair-webapp-nodejs/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.cookieParser [as handle] (/root/NodeApps/acmeair-webapp-nodejs/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
```

**Comment by xiaoshimimi** [comment]
with "requests" enable only will also raise this exception.

**Comment by tobespc** [comment]
@xiaoshimimi will take a look at this and update you later

**Comment by tobespc** [comment]
what are you setting in your acmeair application to use appmetrics ?

**Comment by xiaoshimimi** [comment]
@tobespc will send you mail about this.

**Comment by yuecchen** [comment]
1. Could express probe work in trace mode? if not, can I disable express probe?
2. Which release will include this fix?

**Comment by tobespc** [comment]
the next release , 2.0 will contain this fix and the prove will work in trace mode
