### ISSUE TITLE
appmetrics 2.0.0 lack of critical files

### ISSUE THREAD

**Issue by xiaoshimimi** [RuntimeTools/appmetrics#383]
Tested with Node.js v4.4.5 and v4.7.1 and v6.9.1.  
Steps:
1. run `npm install appmetrics` in application folder
2. add `require('appmetrics');` in the first line of the application. 
3. run application
4. got the following error messages:
```
Error: Cannot find module './heapdump.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/cvt/nodejs/node-v4.7.1-linux-x64/lib/node_modules/appmetrics/index.js:29:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

I tried to copy heapdump.js into node_modules/appmetrics folder, but still lack of heapdump.node file:

```
Error: Cannot find module './heapdump.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/NodeApps/sample-rest-api/pets/node_modules/appmetrics/heapdump.js:15:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

```

**Comment by mattcolegate** [comment]
This looks like an issue with the pre-built binaries that we make available on NPM - I'm not getting it if I install and build from source. Whilst I continue investigations, if you have compilers available you can get on by using `npm install https://github.com/RuntimeTools/appmetrics.git`

**Comment by mattcolegate** [comment]
After investigation, this is definitely several bugs with our processes to build and test pre-built binaries and deliver them to NPM. You won't see any source updates to fix that on here as the code to do that isn't in this repository. The code in this repository is good and can be installed using the method in my last comment, or by downloading the source and installing it locally. We'll get revised binaries up on NPM as soon as possible.

**Comment by mattcolegate** [comment]
Appmetrics v2.0.1 has been released on NPM and verified working on with Node 4 on Windows 64-bit and Linux 64-bit. Please `npm install appmetrics` again and re-test. Please re-open this issue if you experience this problem again.
