### ISSUE TITLE
Node.js v10 cannot be installed in platforms without gcc

### ISSUE THREAD

**Issue by yuecchen** [RuntimeTools/appmetrics#561]
I can install appmetrics with Node.js v10 only when I have gcc installed. 

If the platform doesn't have gcc installed, I will got error:
```
Unsupported version v10.14.0. Trying rebuild.
Falling back to node-gyp rebuild
make: Entering directory `/root/Node/testappmetrics/node_modules/appmetrics/build'
  ACTION binding_gyp_appmetrics_target_Set_appmetrics_reported_version_build_level Release/obj.target/appmetrics/geni/appmetrics.cpp
infile: ./src/appmetrics.cpp
outfile: /root/Node/testappmetrics/node_modules/appmetrics/build/Release/obj.target/appmetrics/geni/appmetrics.cpp
Replacing '"99\.99\.99\.29991231"' with '"4.0.1.201811282023"'
  CXX(target) Release/obj.target/appmetrics/geni/appmetrics.o
make: g++: Command not found
make: *** [Release/obj.target/appmetrics/geni/appmetrics.o] Error 127
make: Leaving directory `/root/Node/testappmetrics/node_modules/appmetrics/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/Node/node10/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 3.10.0-862.11.6.el7.x86_64
gyp ERR! command "/root/Node/node10/bin/node" "/root/Node/node10/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/Node/testappmetrics/node_modules/appmetrics
gyp ERR! node -v v10.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN testappmetrics No description
npm WARN testappmetrics No repository field.
npm WARN testappmetrics No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appmetrics@4.0.1 install: `node extract_all_binaries.js || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appmetrics@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-29T01_33_25_127Z-debug.log

```

I wish appmetrics could be able to provide a similar tgz package as for v8 and v6, so that don't need user to compile it.
e.g.
```
Download and extract of 8/appmetrics-4.0.1-linux-x64.tgz finished.
Download and extract of 8/agentcore-3.2.9-linux-x64.tgz finished.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN testappmetrics No description
npm WARN testappmetrics No repository field.
npm WARN testappmetrics No license field.
+ appmetrics@4.0.1
updated 1 package in 44.02s
```

**Comment by tobespc** [comment]
We are no longer shipping binaries for appmetrics, so anyone installing will be required to have GCC installed
