### ISSUE TITLE
appmetrics cannot be required in Node.js v4.2.2

### ISSUE THREAD

**Issue by xiaoshimimi** [RuntimeTools/appmetrics#86]
I installed appmetrics with Node.js v4.2.2: 
```
npm install -g appmetrics
```
result: 
```
[root@xxxx node_modules]# pwd
/root/Documents/node4/lib/node_modules
[root@xxxx node_modules]# ls
appmetrics  npm
```

Then add **require("appmetrics")** in my application entry, and start my application. It cannot find the global appmetrics: 
```
[root@xxxx acmeair-webapp-nodejs]# /root/Documents/node4/bin/node app
module.js:339
    throw err;
    ^

Error: Cannot find module 'appmetrics'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/root/NodeApps/acmeair-webapp-nodejs/app.js:4:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

Then I use:**require("/root/Documents/node4/lib/node_modules/appmetrics")**, it throw Module did not self-register error
```
[root@xxxx acmeair-webapp-nodejs]# /root/Documents/node4/bin/node app
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/root/Documents/node4/lib/node_modules/appmetrics/index.js:25:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

**Comment by seabaylea** [comment]
Node Application Metrics does work with Node.js v4.x, including v4.2.2. It looks like the issue is around the configuration of which Node.js install to use.

Whilst your using NPM from an install of Node.js 4.2.2, a different level of Node.js is being used to install 'appmetrics' itself. This means that the compiled binaries for 'appmetrics' are for a different level, and that's why the error message is occurring.

Could you try making sure that the Node.js 4.2.2 install is on your path before installing?
eg.
```sh
export PATH=/root/Documents/node4/bin:$PATH
npm install appmetrics
```
and then see if the issue occurs?

**Comment by xiaoshimimi** [comment]
It run successfully when I add the node v4 bin into PATH before run npm install. Problem resolved.
