### ISSUE TITLE
cannot enable('trace') for ghost v0.7.1 application

### ISSUE THREAD

**Issue by xiaoshimimi** [RuntimeTools/appmetrics#87]
If we enable trace, with appmetrics, and run ghost v0.7.1 application, it through exception repeately: 
```
Unhandled rejection TypeError: Cannot read property 'clients' of undefined
    at renderIndex (/opt/node-v0.10.33/sample/ghost_v0.7.1/core/server/controllers/admin.js:22:72)
    at tryCatcher (/opt/node-v0.10.33/sample/ghost_v0.7.1/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/opt/node-v0.10.33/sample/ghost_v0.7.1/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/opt/node-v0.10.33/sample/ghost_v0.7.1/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise.b (domain.js:183:18)
    at Async._drainQueue (/opt/node-v0.10.33/sample/ghost_v0.7.1/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/opt/node-v0.10.33/sample/ghost_v0.7.1/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/opt/node-v0.10.33/sample/ghost_v0.7.1/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback (node.js:463:13)
```
Ghost v0.7.1: 
https://ghost.org/download/

To run ghost application, you must change "127.0.0.1" or "localhost" to your IP, otherwise it cannot be accessed outside this machine.

**Comment by seabaylea** [comment]
I've reproduced this. We'll start working on a fix.

**Comment by hhellyeribm** [comment]
@xiaoshimimi - I've pushed a fix that I believe resolves this issue. (It works for me!) Would you be able to verify it in your environment?

**Comment by tunniclm** [comment]
FYI, #105 has been included in v1.0.4

**Comment by xiaoshimimi** [comment]
The major problem is fixed.  But there is two small problem, which will not broke the application's function, but error messages throw out:

Like
```
ERROR: Object.keys called on non-object
 Checking for updates failed, your blog will continue to function.
 If you get this error repeatedly, please seek help from https://ghost.org/forum.
 TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Promise.f [as catch] (/opt/node-v0.10.33/sample/ghost_v0.7.1/node_modules/ibm-apm/node_modules/appmetrics/probes/trace-probe.js:108:17)
    at updateCheckData (/opt/node-v0.10.33/sample/ghost_v0.7.1/core/server/update-check.js:72:38)
```

The root cause is **sth.hasOwnProperty('prototype')** always **true**, even the prototype is **undefined**.

I changed the line 107 of trace-probe.js:

from
```
 (!arguments[arguments.length-1].hasOwnProperty('prototype') ||
```
to
```
 (!arguments[arguments.length-1].prototype ||
```

And there is still another error message, then I change line 76/77:
from
```
			Object.keys(arg).length == 0 && 
                            Object.keys(arg.prototype).length==0) {
```
to
```
			Object.keys(arg).length == 0 && arg.prototype &&
                            Object.keys(arg.prototype).length==0) {
```

I just tested the code with ghost v0.7, it works fine.

**Comment by hhellyeribm** [comment]
@xiaoshimimi - Can you tell us what you need to do to trigger that exception? That way we can verify the fix really works. (I'm also wondering if we should split this off into a separate issue since we've fixed the original blocking problem.)

**Comment by xiaoshimimi** [comment]
@hhellyeribm - Steps to recreated the exception: 
1) remove *.db in the ghost project /content/data folder
2) start application with appmetrics and trace enabled
3) wait for db is loading finished
4) visit http://<ip>:<port>/ghost

Then the exception appears.

**Comment by xiaoshimimi** [comment]
open another issue https://github.com/RuntimeTools/appmetrics/issues/116
